name: Technical Dept
on: [push]

jobs:
  weakSATDAction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run weakSATD Action
        uses: <account>/WeakSATD-Action@v0.0.3
